# Generated by Django 4.0.3 on 2022-03-12 09:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_banner_cta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_body',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title here :)', max_length=100, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add your text/paragraph here :)', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=True))]))], blank=True, null=True),
        ),
    ]
