# Generated by Django 4.0.3 on 2022-03-11 17:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content_body', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title here :)', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add your text/paragraph here :)', required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'flex page',
                'verbose_name_plural': 'flex pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
