# Generated by Django 4.0.3 on 2022-03-11 17:46

from django.db import migrations
import stream.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_alter_flexpage_content_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content_body',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title here :)', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add your text/paragraph here :)', required=True))])), ('full_richtext', stream.blocks.RichTextBlock()), ('simple_richtext', stream.blocks.SimpleRichTextBlock())], blank=True, null=True),
        ),
    ]
