# Generated by Django 4.0.3 on 2022-03-12 08:38

from django.db import migrations
import stream.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_alter_flexpage_content_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content_body',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title here :)', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add your text/paragraph here :)', required=True))])), ('full_richtext', stream.blocks.RichTextBlock()), ('simple_richtext', stream.blocks.SimpleRichTextBlock()), ('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title here :)', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(help_text='If the button page above is selected, it will be used first.', required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False))])))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title here :)', max_length=100, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add your text/paragraph here :)', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=True))]))], blank=True, null=True),
        ),
    ]
