# Generated by Django 4.0.3 on 2022-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='email address', max_length=500)),
                ('name', models.CharField(help_text='full name', max_length=100)),
            ],
        ),
    ]
